### PR TITLE
fix: make nav buttons use links for accessibility

### LINKED ISSUE #753: Make nav buttons links under the hood (a11y)
The Next, Previous, and jump-to-unit buttons in the Learning MFE are currently buttons that trigger a JS handler, which triggers a redirect.

It would be more semantically friendly to make these into links (under the hood; they will look the same). We can probably do this by passing the next/prev URLs into the code that renders the sequence.

image

### PR DESCRIPTION
**Pull request by mohd-akram**
Closes #753

## Testing instructions

1. Run `npm test`
2. Test the following:
   - Previous and Next buttons in the sequence bar
   - Previous and Next buttons in the unit
   - Unit buttons in the sequence bar
   - Both Previous buttons are disabled in first unit of first section
   - Both Next buttons are disabled in last unit of last section
   - Next button in last unit of last section is enabled and goes to course exit if that is configured

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mohd-akram!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Agrendalath** [comment]
@BbrSofiane, @brian-smith-tcril, would you mind triggering the CI?

**Comment by mohd-akram** [comment]
It didn't seem to run the tests till the end. Failed midway with this:

```
Pact Binary Error: Could not load existing consumer contract from /home/runner/work/frontend-app-learning/frontend-app-learning/src/pacts/frontend-app-learning-lms.json due to undefined method `key?' for nil:NilClass. Creating a new file.
```

File: src/courseware/course/sequence/sequence-navigation/hooks.js [hunk 1]
```diff
@@ -7,19 +7,51 @@ import { sequenceIdsSelector } from '../../../data';
...
+  }
+
+  let previousLink;
+  const previousIndex = unitIndex - 1;
+  if (previousIndex >= 0) {
+    const previousUnitId = sequence.unitIds[previousIndex];
+    previousLink = `/course/${courseId}/${currentSequenceId}/${previousUnitId}`;
+  } else if (previousSequenceId) {
+    previousLink = `/course/${courseId}/${previousSequenceId}/last`;
+  }
```
Comment (farhaanbukhsh) [inline src/courseware/course/sequence/sequence-navigation/hooks.js:52]: We can probably have two functions, getNextLink, getPreviousLink, and the logic can be moved into them, it will help to maintain the code and to find them. What do you think?

File: src/courseware/CoursewareContainer.jsx [hunk 2]
```diff
@@ -254,34 +254,25 @@ class CoursewareContainer extends Component {
...
     }
   };
 
-  handlePreviousSequenceClick = () => {
-    const { previousSequence, courseId } = this.props;
-    if (previousSequence !== null) {
-      history.push(`/course/${courseId}/${previousSequence.id}/last`);
-    }
-  };
+  handlePreviousSequenceClick = () => {};
```
Comment (0x29a) [inline src/courseware/CoursewareContainer.jsx:275]: Since this function is empty, do we still need it?

File: src/courseware/course/sequence/Sequence.jsx [hunk 3]
```diff
@@ -150,19 +146,18 @@ const Sequence = ({
           sequenceId={sequenceId}
           unitId={unitId}
           className="mb-4"
-          nextSequenceHandler={() => {
+          nextHandler={() => {
```
Comment (0x29a) [inline src/courseware/course/sequence/Sequence.jsx:149]: What's the reason behind renaming `nextSequenceHandler` to `nextHandler`? Aren't these buttons still supposed to lead to a "next sequence"?

File: src/courseware/course/sequence/Sequence.jsx [hunk 4]
```diff
@@ -150,19 +146,18 @@ const Sequence = ({
...
             logEvent('edx.ui.lms.sequence.next_selected', 'top');
             handleNext();
           }}
           onNavigate={(destinationUnitId) => {
             logEvent('edx.ui.lms.sequence.tab_selected', 'top', destinationUnitId);
             handleNavigate(destinationUnitId);
           }}
-          previousSequenceHandler={() => {
+          previousHandler={() => {
```
Comment (0x29a) [inline src/courseware/course/sequence/Sequence.jsx:157]: Same question as about `nextSequenceHandler`.

**Review by 0x29a — APPROVED** [review]
:+1:

- [x] I tested this: all buttons work and show as expected.
- [x] I read through the code.
- [x] This MFE is now more accessible. :slightly_smiling_face:

File: src/courseware/CoursewareContainer.jsx (hunk 2 above)
Comment (mohd-akram) [reply src/courseware/CoursewareContainer.jsx:275]: Not really, I only left it for symmetry with the next handler and as a stable reference (it's a required prop in `<Course>`).

File: src/courseware/course/sequence/Sequence.jsx (hunk 3 above)
Comment (mohd-akram) [reply src/courseware/course/sequence/Sequence.jsx:149]: They lead to the next unit. They only lead to the next sequence if it's the last unit in the sequence.

File: src/courseware/course/sequence/Sequence.jsx (hunk 4 above)
Comment (mohd-akram) [reply src/courseware/course/sequence/Sequence.jsx:157]: Same reason as `nextHandler`.

File: src/courseware/course/sequence/sequence-navigation/hooks.js (hunk 1 above)
Comment (mohd-akram) [reply src/courseware/course/sequence/sequence-navigation/hooks.js:52]: We could, but it will duplicate some logic (eg. isLastUnit). I'm also not sure where I'd put them.

**Comment by mohd-akram** [comment]
> It didn't seem to run the tests till the end. Failed midway with this:
> 
> ```
> Pact Binary Error: Could not load existing consumer contract from /home/runner/work/frontend-app-learning/frontend-app-learning/src/pacts/frontend-app-learning-lms.json due to undefined method `key?' for nil:NilClass. Creating a new file.
> ```

If anyone has any idea how to fix this or if it's just an intermittent error, re-run the tests, that would be appreciated.

EDIT: I've verified that this is an intermittent error and the tests [should pass](https://github.com/mohd-akram/frontend-app-learning/actions/runs/5517211766/jobs/10059525434).

**Comment by 0x29a** [comment]
@BbrSofiane, @brian-smith-tcril, could you please trigger the CI again?

**Comment by itsjeyd** [comment]
@mohd-akram Thank you for this contribution!

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: tested the navigation locally
* [x] I read through the code
* [x] I checked for accessibility issues
* [x] Includes documentation: n/a
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Comment by Agrendalath** [comment]
@BbrSofiane, @brian-smith-tcril, would you like to review this as CC? It closes an issue reported in this repo (#753).

File: src/courseware/course/sequence/sequence-navigation/hooks.js (hunk 1 above)
Comment (xitij2000) [reply src/courseware/course/sequence/sequence-navigation/hooks.js:52]: I think you can create a series of interdependent hooks. 

i.e. useNextLink, and usePreviousLink, that can both use common hooks. i.e. they can both pull in use a common hook that returns isLastUnit

**Comment by itsjeyd** [comment]
@mattcarter FYI^^

Please let us know if you're planning to have someone from the Aurora team look at these changes as well.

**Comment by itsjeyd** [comment]
Hey @BbrSofiane and @brian-smith-tcril, friendly ping about @Agrendalath's question [above](https://github.com/openedx/frontend-app-learning/pull/1137#issuecomment-1633078771).

CC @mattcarter

File: src/courseware/course/Course.test.jsx [hunk 5]
```diff
@@ -280,8 +280,8 @@ describe('Course', () => {
 
     loadUnit();
     await waitFor(() => expect(screen.queryByText('Loading learning sequence...')).not.toBeInTheDocument());
-    screen.getAllByRole('button', { name: /previous/i }).forEach(button => fireEvent.click(button));
-    screen.getAllByRole('button', { name: /next/i }).forEach(button => fireEvent.click(button));
+    screen.getAllByRole('link', { name: /previous/i }).forEach(button => fireEvent.click(button));
+    screen.getAllByRole('link', { name: /next/i }).forEach(button => fireEvent.click(button));
```
Comment (brian-smith-tcril) [inline src/courseware/course/Course.test.jsx]: functionally identical but just for naming consistency

```suggestion
    screen.getAllByRole('link', { name: /previous/i }).forEach(link => fireEvent.click(link));
    screen.getAllByRole('link', { name: /next/i }).forEach(link => fireEvent.click(link));
```

File: src/courseware/course/sequence/Sequence.jsx [hunk 6]
```diff
@@ -150,19 +146,18 @@ const Sequence = ({
...
             logEvent('edx.ui.lms.sequence.previous_selected', 'top');
             handlePrevious();
           }}
-          goToCourseExitPage={() => goToCourseExitPage()}
```
Comment (brian-smith-tcril) [inline src/courseware/course/sequence/Sequence.jsx:165]: I'd just like to confirm I'm understanding 
> Next button in last unit of last section is enabled and goes to course exit if that is configured

from https://github.com/openedx/frontend-app-learning/pull/1137#issue-1793006174 correctly. Since that is the case it means we no longer need `gotToCourseExitPage` at all?

File: src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx [hunk 7]
```diff
@@ -1,4 +1,5 @@
 import React from 'react';
+import { Link } from 'react-router-dom';
```
Comment (brian-smith-tcril) [inline src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx:2]: Is there a reason we aren't already using these? This feels like it simplifies the implementation quite a bit (which I'm all for!). I'm worried I don't have enough context on the original implementation to know if that was an intentional architectural decision or not. I'm just not sure if there's something I'm missing that prevented use of react-router links in the first place.

**Review by brian-smith-tcril — COMMENTED** [review]
Thank you so much for this! I left a few comments with questions, but overall this is looking great!

File: src/courseware/course/sequence/Sequence.jsx (hunk 6 above)
Comment (mohd-akram) [reply src/courseware/course/sequence/Sequence.jsx:165]: `goToCourseExitPage` simply redirected to the exit URL when clicking next on the last unit. This is now handled in the `useSequenceNavigationMetadata` hook so I removed it.

File: src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx (hunk 7 above)
Comment (mohd-akram) [reply src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx:2]: No idea. I can see that react router links are used in some other places (eg. CourseBreadcrumbs).

**Comment by itsjeyd** [comment]
@mohd-akram Looks like this is getting close to merging! If you could fix the remaining `commitlint` failure, we should get a green build here.

CC @brian-smith-tcril

**Comment by mohd-akram** [comment]
Fixed.

**Review by muselesscreator — APPROVED** [review]
From high level, LGTM

**Comment by openedx-webhooks** [comment]
@mohd-akram 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1137&entry.1484655318=https://github.com/mohd-akram&entry.752974735=2023-07-07+07:57&entry.1917517419=2023-08-14+17:18&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by kdmccormick** [comment]
Thanks @mohd-akram ! 🎉
